pub fn get_sentences_dvorak() -> Vec<String> {
    vec![
        "aoe aoe aoe",
        "aoe ui aoe ui",
        "aoi ue aoi ue",
        "aoe dhtns aoe",
        "dhtns aoe dhtns",
        "aoe aoe dhtns",
        "aoe ui dhtn",
        "dhtn aoe ui",
        "aoe dht aoe",
        "aoe nst aoe",
        "ao dht ao dht",
        "eui ns eui ns",
        "aoe ht aoe ht",
        "ui dns ui dns",
        "aoe tnh aoe",
        "aoe sn aoe sn",
        "aoe ht sn aoe",
        "aoe dhtns ui",
        "ui aoe dhtns",
        "aoe ui sn ht",
        "ao ao ui ui",
        "ht ht sn sn",
        "dht dht aoe",
        "aoe aoe ui ui",
        "dhtns dhtns",
        "aoe dht aoe",
        "ui sn ui sn",
        "ht ao ht ao",
        "sn ui sn ui",
        "dht aoe dht",
        "time and again",
        "make it work",
        "keep it going",
        "find a way",
        "use the data",
        "move it fast",
        "take the lead",
        "feel the flow",
        "keep control",
        "work as one",
        "the system works well",
        "use the right data",
        "make time to learn",
        "keep the code clean",
        "find the best way",
        "move at a steady pace",
        "take control of it",
        "work with the team",
        "feel the right flow",
        "use time wisely",
        "clean code matters",
        "simple logic works",
        "data drives results",
        "test the system",
        "fix the issue",
        "build the tool",
        "keep things simple",
        "avoid bad habits",
        "learn by doing",
        "improve with practice",
        "make make time",
        "take take time",
        "keep keep going",
        "find find way",
        "use use data",
        "move move fast",
        "work work well",
        "feel feel good",
        "test test code",
        "build build tools",
        "make time to practice daily",
        "keep the system simple and clean",
        "use the data to find trends",
        "work with focus and intent",
        "move forward one step at a time",
        "take control and stay calm",
        "learn the skill through practice",
        "test the code before release",
        "improve speed without errors",
        "build habits that last",
        "the system works when the code is clean",
        "make time every day to improve skills",
        "use clear logic and simple structure",
        "move fast but keep control",
        "practice typing with steady rhythm",
        "accuracy matters more than speed",
        "build muscle memory with care",
        "learn patterns and repeat them",
        "keep hands relaxed and focused",
        "improve flow through repetition",
        "time time time",
        "and and and",
        "the the the",
        "make make make",
        "data data data",
        "code code code",
        "work work work",
        "move move move",
        "keep keep keep",
        "learn learn learn",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect()
}
