pub fn get_sentences_normal() -> Vec<String> {
    vec![
        "The quick brown fox jumps over the lazy dog. This sentence contains every letter of the alphabet.",
        "Programming is the art of telling another human what one wants the computer to do.",
        "In programming, the hard part isn't solving problems, but deciding what problems to solve.",
        "Code is like humor. When you have to explain it, it's bad.",
        "First, solve the problem. Then, write the code.",
        "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
        "Experience is the name everyone gives to their mistakes.",
        "Java is to JavaScript what car is to Carpet.",
        "There are only two hard things in Computer Science: cache invalidation and naming things.",
        "Walking on water and developing software from a specification are easy if both are frozen.",
        "Programming is the process of turning ideas into bugs, then bugs into features.",
        "Code exists to be read, not just to be executed.",
        "A program that works is good; a program that is understood is better.",
        "Software complexity grows until it exceeds human patience.",
        "Every abstraction leaks, but some leak less often.",
        "The fastest code is the code you don’t need to run.",
        "Computers are fast, but bad assumptions are faster.",
        "Writing code is easy; deciding what not to write is hard.",
        "Good software design is mostly about saying no.",
        "Programs fail in production, not in theory.",
        "Code that solves today’s problem often creates tomorrow’s problem.",
        "Premature optimization is optimism in disguise.",
        "A compiler is a very strict reader.",
        "Code reviews exist because humans make consistent mistakes.",
        "Software breaks silently before it breaks loudly.",
        "Every dependency is a future problem waiting politely.",
        "Code duplication is a tax you pay with interest.",
        "The simplest solution is usually the last one considered.",
        "Software engineering is managing trade-offs, not perfection.",
        "Machines follow instructions perfectly; humans rarely give perfect instructions.",
        "A bug fixed twice was never fixed the first time.",
        "Clean code feels slower to write and faster to live with.",
        "If it works on your machine, your machine is special.",
        "Refactoring is changing code without changing behavior—ideally.",
        "Documentation is a letter to your future self.",
        "Code ages faster than comments.",
        "Systems fail at their boundaries, not their centers.",
        "Complexity hides where names are unclear.",
        "Every feature request is a design test.",
        "Error handling is the difference between theory and reality.",
        "Code that cannot fail has not been tested enough.",
        "Automation replaces repetition, not responsibility.",
        "A program is correct until the inputs change.",
        "Tests don’t prove correctness; they reduce fear.",
        "APIs are promises that must be kept.",
        "A slow algorithm stays slow on faster hardware.",
        "Code readability is a performance feature for humans.",
        "The hardest bugs are logical, not syntactic.",
        "Software architecture is frozen assumptions.",
        "Good naming solves half the problem.",
        "Debug logs are conversations with the past.",
        "The cost of change grows with silence.",
        "A working hack is still a hack tomorrow.",
        "Programs do exactly what you tell them, not what you mean.",
        "Simplicity is achieved, not added.",
        "Code reuse saves time until it doesn’t.",
        "Software design is deciding where complexity is allowed.",
        "The user is always right about the problem, not the solution.",
        "Code that is easy to change is rarely accidental.",
        "Bugs hide in assumptions, not lines of code.",
        "Good software feels boring when it works.",
        "Performance problems appear where measurement was skipped.",
        "Software failures are usually human failures first.",
        "The best code explains itself before it runs.",
        "Systems become legacy faster than expected.",
        "Writing code is cheaper than maintaining it—once.",
        "The first version teaches what the second should be.",
        "Code structure reflects team structure.",
        "The hardest part of programming is stopping.",
        "Software evolves until it becomes unrecognizable.",
        "A crash is just feedback with poor timing.",
        "Every workaround becomes permanent eventually.",
        "Software bugs are just misplaced confidence.",
        "Debugging ends when understanding begins.",
        "The best abstractions feel obvious in hindsight.",
        "Code is a conversation between present and future developers.",
        "Technical debt grows silently during success.",
        "Software correctness is a moving target.",
        "A failing test is a gift wrapped in frustration.",
        "Programs grow by addition but improve by removal.",
        "Software design is predicting regret.",
        "The hardest problems are the ones users don’t describe well.",
        "A system is secure until it is popular.",
        "Code reviews teach more than documentation.",
        "Software errors rarely travel alone.",
        "Writing code is thinking out loud in syntax.",
        "Every shortcut creates a longer road later.",
        "Software is fragile where it is assumed stable.",
        "The best refactor changes less than expected.",
        "Programs don’t get tired; developers do.",
        "A feature without tests is a suggestion.",
        "Software reliability is built, not hoped for.",
        "Complexity is easy to add and hard to remove.",
        "Code is precise, but requirements are not.",
        "Software design ends when constraints appear.",
        "A good system fails predictably.",
        "Code smells are warnings, not errors.",
        "The best optimization is deleting code.",
        "Software maintenance is delayed design.",
        "Programs reflect how their authors think.",
        "Bugs prefer quiet code paths.",
        "A stable API is harder than fast code.",
        "Software grows until someone simplifies it.",
        "Code clarity is kindness to future developers.",
        "Programming is teaching machines while learning about humans.",
        "Programming turns ideas into machines that think for you.",
        "Code is the bridge between logic and reality.",
        "A bug is just a misunderstood instruction.",
        "Software is never finished, only abandoned or deployed.",
        "Every program starts as a guess about the future.",
        "Debugging is detective work with infinite suspects.",
        "Good code reads like a conversation with your future self.",
        "Complexity is the tax you pay for power.",
        "Simplicity is the ultimate optimization.",
        "The best algorithm is the one you understand.",
        "A compiler never lies, but it rarely explains.",
        "Tests are proof that your assumptions survived reality.",
        "Documentation is code written for humans first.",
        "Performance problems hide where assumptions live.",
        "Code without structure is a story without grammar.",
        "The fastest fix is usually the wrong one.",
        "Naming things is architecture disguised as vocabulary.",
        "Refactoring is rewriting history with better decisions.",
        "Every feature begins as a liability.",
        "Abstraction is choosing what not to think about.",
        "Software scales faster than understanding.",
        "Data never lies, but it rarely tells the whole truth.",
        "A function is a promise wrapped in syntax.",
        "The hardest bugs reproduce only when you’re not watching.",
        "Design patterns are reusable mistakes made official.",
        "Code reviews are empathy in executable form.",
        "Premature optimization is the art of guessing wrong early.",
        "The best comment is the one your code doesn’t need.",
        "APIs are contracts written in hope.",
        "Every dependency is a future negotiation.",
        "A clean commit tells a better story than a clever hack.",
        "The computer is fast; your assumptions are slower.",
        "Legacy code is just code that survived.",
        "Concurrency is cooperation without communication.",
        "A null pointer is uncertainty wearing a disguise.",
        "Software architecture is frozen decision-making.",
        "A loop is a thought that refuses to stop.",
        "Bugs prefer corners humans forget to look at.",
        "Code evolves faster than the problems it solves.",
        "Every crash is feedback delivered loudly.",
        "Automation is laziness elevated to engineering.",
        "Technical debt is interest on rushed decisions.",
        "A variable is memory with a name and a purpose.",
        "Consistency beats cleverness every time.",
        "Code is communication with machines mediated by humans.",
        "The best architecture is invisible to its users.",
        "A framework is a shortcut with opinions.",
        "Reusability begins where ego ends.",
        "Software fails gracefully only when designed humbly.",
        "The hardest part of programming is deciding what not to build.",
        "A feature without tests is a rumor.",
        "Every interface hides a story of compromise.",
        "Scalability starts as optimism and ends as discipline.",
        "Code duplication is memory refusing to share.",
        "A pull request is a conversation in diff format.",
        "Algorithms are poetry written in logic.",
        "The keyboard is the programmer’s laboratory.",
        "Constraints turn creativity into engineering.",
        "A good error message teaches more than success ever could.",
        "Refactoring is cleaning while the house is on fire.",
        "A constant is a belief you refuse to question.",
        "The best tools disappear when you use them.",
        "Programming is thinking with a compiler watching.",
        "Code smells are intuition translated into discomfort.",
        "A test suite is a memory that never forgets.",
        "Software grows like a city without zoning laws.",
        "Every optimization sacrifices clarity somewhere else.",
        "A commit history is a timeline of evolving understanding.",
        "The hardest problems hide behind easy names.",
        "Debugging is meditation interrupted by logic.",
        "Code without purpose is noise in structured form.",
        "The best engineers delete more code than they write.",
        "Documentation is time travel for future developers.",
        "A deadline is a feature disguised as pressure.",
        "The most dangerous word in programming is “probably.”",
        "Software is empathy expressed through systems.",
        "A design decision is a prediction about tomorrow.",
        "A build system is a ritual of trust.",
        "The simplest API is the one you don’t need to explain.",
        "Every shortcut eventually becomes the long road.",
        "Code clarity is kindness to strangers.",
        "A runtime error is logic asking for forgiveness.",
        "Programming languages are philosophies wearing syntax.",
        "The best solutions feel obvious only after discovery.",
        "A crash log is a confession written by the machine.",
        "The real cost of code is reading it later.",
        "Performance tuning is archaeology with benchmarks.",
        "A repository is memory with version control.",
        "A codebase reflects the team that built it.",
        "Software architecture is storytelling at scale.",
        "A build that passes locally is optimism in action.",
        "The most reliable code is the code never executed.",
        "Every bug teaches humility disguised as frustration.",
        "Programming is sculpting logic from uncertainty.",
        "A good abstraction feels boring in the best way.",
        "The hardest part of learning to code is learning to think.",
        "Every deployment is a leap of faith with logs.",
        "Code is frozen thought waiting to be executed.",
        "Great software is curiosity turned into structure."        
    ]
    .iter()
    .map(|s| s.to_string())
    .collect()
}
