pub fn get_sentences_qwerty() -> Vec<String> {
    vec![
        "asdf jkl asdf",
        "a s d f j k l",
        "asdf asdf jkl",
        "fj dj sk al",
        "da fa ja la",
        "lk kj hj gj",
        "ad fs jk l;",
        "sa df jk l;",
        "fa da la ;l",
        "as jl dk f;",
        "did you",
        "had to",
        "we are",
        "it is",
        "you can",
        "they are",
        "I will",
        "do not",
        "we will",
        "you did",
        "th th th",
        "he he he",
        "in in in",
        "er er er",
        "an an an",
        "re re re",
        "on on on",
        "at at at",
        "en en en",
        "nd nd nd",
        "the the the",
        "and and and",
        "ing ing ing",
        "her her her",
        "tha tha tha",
        "ent ent ent",
        "ion ion ion",
        "for for for",
        "ere ere ere",
        "ter ter ter",
        "the time",
        "and then",
        "in the",
        "on the",
        "for the",
        "with you",
        "from here",
        "by the",
        "at the",
        "to the",
        "wer ert",
        "try type",
        "write here",
        "query text",
        "quiet try",
        "power write",
        "where were",
        "type quickly",
        "read your",
        "zxc vbn",
        "zoom back",
        "next value",
        "basic level",
        "zero cost",
        "move back",
        "value box",
        "cover zone",
        "very basic",
        "exact value",
        "type faster",
        "keep rhythm",
        "control errors",
        "steady pace",
        "clean input",
        "correct form",
        "even speed",
        "smooth flow",
        "clear text",
        "fixed focus",
        "value time form",
        "form value time",
        "speed rhythm flow",
        "flow speed rhythm",
        "rhythm flow speed",
        "input process output",
        "output input process",
        "process output input",
        "hands stay relaxed",
        "fingers stay centered",
        "eyes on screen",
        "no looking down",
        "accuracy before speed",
        "light key presses",
        "even hand balance",
        "no wasted motion",
        "clean repetitions",
        "stable typing form",
        "controlled fast typing",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect()
}
